name: Missing Changelog Reminder
description: Reminds users to add a changelog if their pull request is missing one
author: Mark Skelton
branding:
  icon: check
  color: green
inputs:
  changelogRegex:
    description: Regex pattern to match the changelog
    default: CHANGELOG\.md
  message:
    description: Message to display if no changelog is found
    default: "@${{ github.actor }} your pull request is missing a changelog!"
  token:
    description: "GITHUB_TOKEN used to authenticate requests. Since there's a default, this is typically not supplied by the user."
    default: ${{ github.token }}
runs:
  using: node12
  main: dist/index.js
