name: Compile
on:
  push:
    branches: [main]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: mskelton/setup-yarn@v1
      - run: yarn build
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update build artifact
